// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/advisors/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/advisors/[id].get').default>>>>
    }
    '/api/advisors': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/advisors/index.get').default>>>>
    }
    '/api/projects/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/projects/[id].get').default>>>>
    }
    '/api/projects': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/projects/index.get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}