// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 9/22/2026, 5:06:21 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["C:/Users/mmham/Downloads/rechitta-app-scaffold/rechitta-app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/mmham/Downloads/rechitta-app-scaffold/rechitta-app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/mmham/Downloads/rechitta-app-scaffold/rechitta-app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/mmham/Downloads/rechitta-app-scaffold/rechitta-app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/mmham/Downloads/rechitta-app-scaffold/rechitta-app/plugins/**/*.{js,ts,mjs}","C:/Users/mmham/Downloads/rechitta-app-scaffold/rechitta-app/composables/**/*.{js,ts,mjs}","C:/Users/mmham/Downloads/rechitta-app-scaffold/rechitta-app/utils/**/*.{js,ts,mjs}","C:/Users/mmham/Downloads/rechitta-app-scaffold/rechitta-app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/mmham/Downloads/rechitta-app-scaffold/rechitta-app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/mmham/Downloads/rechitta-app-scaffold/rechitta-app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/mmham/Downloads/rechitta-app-scaffold/rechitta-app/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;